version: '3'

services:
  postgres:
    container_name: ch_postgres
    image: postgres:12.5-alpine
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: '"conference-hall","conference-hall-test"'
      POSTGRES_HOST_AUTH_METHOD: trust
